#!/bin/bash

source extended_apis/tools/common.sh

source extended_apis/tools/config_io.sh
source extended_apis/tools/config_msr.sh
source extended_apis/tools/config_vpid.sh
source extended_apis/tools/config_rdrand.sh
source extended_apis/tools/config_rdseed.sh
source extended_apis/tools/config_wbinvd.sh
source extended_apis/tools/config_rdpmc.sh
source extended_apis/tools/config_rdtsc.sh
source extended_apis/tools/config_invlpg.sh
source extended_apis/tools/config_desc_table.sh
source extended_apis/tools/config_cr3.sh
source extended_apis/tools/config_cr4.sh
source extended_apis/tools/config_cr8_store.sh
source extended_apis/tools/config_cr8_load.sh
source extended_apis/tools/config_ept.sh
source extended_apis/tools/config_mov_dr.sh

config_cores() {

    case "$1" in
    "io")
        if [[ $# -lt 2 ]]; then io_usage; exit 0; fi
        config_io $@
        ;;
    "rdmsr"|"wrmsr")
        if [[ $# -lt 2 ]]; then msr_usage; exit 0; fi
        config_msr $@
        ;;
    "vpid")
        if [[ $# -lt 2 ]]; then vpid_usage; exit 0; fi
        config_vpid $@
        ;;
    "rdrand")
        if [[ $# -lt 2 ]]; then rdrand_usage; exit 0; fi
        config_rdrand $@
        ;;
    "rdseed")
        if [[ $# -lt 2 ]]; then rdseed_usage; exit 0; fi
        config_rdseed $@
        ;;
    "wbinvd")
        if [[ $# -lt 2 ]]; then wbinvd_usage; exit 0; fi
        config_wbinvd $@
        ;;
    "rdpmc")
        if [[ $# -lt 2 ]]; then rdpmc_usage; exit 0; fi
        config_rdpmc $@
        ;;
    "rdtsc"|"rdtscp")
        if [[ $# -lt 2 ]]; then rdtsc_usage; exit 0; fi
        config_rdtsc $@
        ;;
    "invlpg"|"invpcid")
        if [[ $# -lt 2 ]]; then invlpg_usage; exit 0; fi
        config_invlpg $@
        ;;
    "desc-table")
        if [[ $# -lt 2 ]]; then desc_table_usage; exit 0; fi
        config_desc_table $@
        ;;
    "cr3")
        if [[ $# -lt 2 ]]; then cr3_usage; exit 0; fi
        config_cr3 $@
        ;;
    "cr4")
        if [[ $# -lt 2 ]]; then cr4_usage; exit 0; fi
        config_cr4 $@
        ;;
    "cr8-store")
        if [[ $# -lt 2 ]]; then cr8_store_usage; exit 0; fi
        config_cr8_store $@
        ;;
    "cr8-load")
        if [[ $# -lt 2 ]]; then cr8_load_usage; exit 0; fi
        config_cr8_load $@
        ;;
    "ept")
        if [[ $# -lt 2 ]]; then ept_usage; exit 0; fi
        config_ept $@
        ;;
    "mov-dr")
        if [[ $# -lt 2 ]]; then mov_dr_usage; exit 0; fi
        config_mov_dr $@
        ;;
    *)
        echo -e ""$CR"error"$CE": live $1 configuration is unsupported"
        ;;
    esac
}

if [[ $# -eq 0 ]]; then
    echo -e ""$CC"usage"$CE": ./vmconfig <category> (lists options & syntax specific to <category>)"
    echo -e ""$CY"syntax"$CE": <category> = io | rdmsr | wrmsr | vpid | rdrand |"
    echo -e ""$CY"syntax"$CE":              rdseed | wbinvd | rdpmc | rdtsc |"
    echo -e ""$CY"syntax"$CE":              rdtscp | invlpg | invpcid | desc-table |"
    echo -e ""$CY"syntax"$CE":              cr3 | cr8-store | cr8-load |"
    echo -e ""$CY"syntax"$CE":              ept | mov-dr | cr4"
    exit 0
fi

config_cores $@
