#!/bin/bash

source extended_apis/tools/common.sh

source extended_apis/tools/config_io.sh
source extended_apis/tools/config_msr.sh
source extended_apis/tools/config_vpid.sh
source extended_apis/tools/config_rdrand.sh
source extended_apis/tools/config_rdseed.sh
source extended_apis/tools/config_wbinvd.sh
source extended_apis/tools/config_rdpmc.sh

config_cores() {

    case "$1" in
    "io")
        if [[ $# -lt 2 ]]; then io_usage; exit 0; fi
        config_io $@
        ;;
    "rdmsr"|"wrmsr")
        if [[ $# -lt 2 ]]; then msr_usage; exit 0; fi
        config_msr $@
        ;;
    "vpid")
        if [[ $# -lt 2 ]]; then vpid_usage; exit 0; fi
        config_vpid $@
        ;;
    "rdrand")
        if [[ $# -lt 2 ]]; then rdrand_usage; exit 0; fi
        config_rdrand $@
        ;;
    "rdseed")
        if [[ $# -lt 2 ]]; then rdseed_usage; exit 0; fi
        config_rdseed $@
        ;;
    "wbinvd")
        if [[ $# -lt 2 ]]; then wbinvd_usage; exit 0; fi
        config_wbinvd $@
        ;;
    "rdpmc")
        if [[ $# -lt 2 ]]; then rdpmc_usage; exit 0; fi
        config_rdpmc $@
        ;;
    *)
        echo -e ""$CR"error"$CE": live $1 configuration is unsupported"
        ;;
    esac
}

if [[ $# -eq 0 ]]; then
    printf ""$CY"syntax"$CE": ./vmconfig <cat> for category-specific"
    printf " syntax \n"
    echo -e ""$CY"syntax"$CE": <cat> = io | rdmsr | wrmsr | vpid | rdrand | rdseed"
    echo -e ""$CY"syntax"$CE":       | wbinvd | rdpmc"
    exit 0
fi

config_cores $@
